modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Void Miners Remastered"
updateJSONURL=""
displayURL="https://github.com/SrNadien/VoidMiners"
logoFile=""
credits=""
authors="${mod_authors}"

description='''${mod_description}'''


[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
   versionRange="[${kubejs_version},)"
    ordering="AFTER"
    side="BOTH"